name: Build and upload executable

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "src/*.rs"
      - "Cargo.toml"
      - ".github/workflow/*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - uses: actions/checkout@v3
      name: Upload artifact
      with:
        name: everything-${{ matrix.os }}
        path: target/release/everything

